config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resources :retweets
    resources :likes, only: [ :create, :destroy]
  end
  
  # Creating these for using .js.erb for displaying likes adn retweets in root_path
  get '/displaylikes/:id', to: 'tweets#display_likes', as: :display_likes
  get '/displayretweets/:id', to: 'tweets#display_retweets', as: :display_retweets

  namespace :auths do
    get '/users/signup', to: 'users#new'
    resources :users, except: :new

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end
  root 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  MIN_RTWEET_LENGTH = 1
  MAX_RTWEET_LENGTH = 100
  belongs_to :tweet
  belongs_to :user
  validates :rtweet, presence: true, length: {in: (MIN_RTWEET_LENGTH)..(MAX_RTWEET_LENGTH)}
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
    before_action :find_retweet, except: [:create]
    before_action :correct_user, only: [:destroy, :edit, :update]

    def create
        tweet = Tweet.find(params[:tweet_id])
        retweet = tweet.retweets.create(retweet_params)
        retweet.user = current_user

        if retweet.save
            redirect_to tweet
        else
            session_alert('alert', retweet.errors.full_messages.to_sentence, tweet)
        end
    end

    def destroy
        @retweet.destroy
        redirect_to tweet_path(@retweet.tweet)
    end

    def edit
        @tweet = @retweet.tweet
    end

    def update
        @tweet = @retweet.tweet
        if @retweet.update(retweet_params)
            redirect_to tweet_path(@tweet)
        else
            render :edit
        end
    end

    private 

    def retweet_params
        params.require(:retweet).permit(:rtweet)
    end

    def find_retweet
        @retweet = Retweet.find(params[:id])
    end

    def correct_user
        unless user_equals?(@retweet.user) || user_equals?(@retweet.tweet.user) 
            session_alert('alert', 'You dont have permission!', @retweet.tweet)
        end
    end
end

app/helpers/retweets_helper.rb
module RetweetsHelper
end

app/views/retweets/_form.html.erb
<% if retweets.errors.any? %>
    <article class="media">
        <div class="media-content is-danger">
        <% retweets.errors.full_messages.each do |err|%>
            <h1> <%= err %> </h1>
        <% end %>
        </div>
    </article>
<% end %>
<article class="media">
    <figure class="media-left">
        <p class="image is-64x64">
        <img src="https://bulma.io/images/placeholders/128x128.png">
        </p>
    </figure>
    <div class="media-content">
        <%= form_with(model:[tweet, retweets], local: true) do |form| %>
            <div class="field">
                <p class="control">
                    <%= form.text_area :rtweet, class:"textarea",placeholder:"Retweet..." %>
                </p>
            </div>
            <div class="field">
                <p class="control">
                    <%= form.submit 'Retweet',class:"button" %>
                </p>
            </div>
        <% end %>
    </div>
</article>

app/views/retweets/_retweet.html.erb
<article class="media">
    <figure class="media-left">
        <p class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png">
        </p>
    </figure>
    <div class="media-content">
        <div class="content">
          <p>
            <strong><%= retweet.user.name %></strong>
            <br>
            <%= retweet.rtweet %>
            <br>
            <% if logged_in? && ( user_equals?(retweet.user) || user_equals?(retweet.tweet.user) ) %>
              <small> <%= link_to 'Edit',edit_tweet_retweet_path(retweet.tweet, retweet) %> · <%= link_to 'Delete', tweet_retweet_path(retweet.tweet_id, retweet),method: :delete,data: { confirm: "Are u sure?"} %> · <%= time_ago_in_words(retweet.created_at) %> ago</small>
            <% end %>
          </p>
        </div>
    </div>
</article>

app/views/retweets/edit.html.erb
<br>
<div class="columns is-multiline">  
    <div class="column is-6 is-offset-3">
        <%= render 'form', tweet: @tweet, retweets: @retweet %>
    </div>
</div>