config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resources :retweets
    resources :likes, only: [ :create, :destroy]
  end
  
  # Creating these for using .js.erb for displaying likes adn retweets in root_path
  get '/displaylikes/:id', to: 'tweets#display_likes', as: :display_likes
  get '/displayretweets/:id', to: 'tweets#display_retweets', as: :display_retweets

  namespace :auths do
    get '/users/signup', to: 'users#new'
    resources :users, except: :new

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end
  root 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    MIN_TWEET_LENGTH = 8
    MAX_TWEET_LENGTH = 50
    has_many :retweets, dependent: :destroy
    has_many :likes, dependent: :delete_all

    belongs_to :user
    validates :tweet,presence: true, length: { in: (MIN_TWEET_LENGTH)..(MAX_TWEET_LENGTH) }
end
 

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show, :display_likes, :display_retweets]
  before_action :find_tweet, except: [:index, :new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @tweets = Tweet.all
  end

  def show
    @retweets = @tweet.retweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to root_path
  end

  def display_likes
    respond_to do |format|
      format.js 
      format.json { render json: @tweet }
    end
  end 

  def display_retweets
    respond_to do |format|
      format.js 
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:tweet)
  end
  
  def find_tweet
    @tweet = Tweet.find(params[:id])
  end

  def correct_user
    unless user_equals?(@tweet.user)
        flash[:danger] = "You dont have permission!"
        redirect_to root_path
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<br>
<div class="section">
<div class="columns">
    <div class="column is-6 is-offset-3">
        <%= form_with model: tweet, local: true do |form| %>
            <div class="field">
                <%= form.label :tweet, class:"label" %>
                <p class="control">

                    <%= form.text_field :tweet, class:"textarea", placeholder:"Your tweet" %>
                    <% if tweet.errors.any? %>
                        <% tweet.errors.full_messages.each do |msg| %>
                            <p class="is-danger"> <%= msg %> </p>
                        <% end %>
                    <% end %>
                </p>
            </div>
            
            <div class="field">
                <p class="control">
                    <%= form.submit button_name, class: 'button is-dark' %>
                    <%= link_to 'Cancel', our_path,class: 'button is-light' %>
                </p>
            </div>
        <% end %>
    </div>
</div>
</div>

app/views/tweets/_header.html.erb
<section class="hero is-primary is-medium">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to 'All tweets', tweets_path,class: 'navbar-item is-active' %>
            
            <%= link_to 'Create tweets', new_tweet_path, class: 'navbar-item' %>
            <a class="navbar-item">
              About
            </a>
            
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <%= title_name %> 
      </h1>
    </div>
  </div>

</section>

app/views/tweets/_six_tweets.html.erb
<div class="column is-3">
    <div class="card four__header">
        <header class="card-header">
            <div class="box" style="width: 100%">
                <article class="media">
                    <figure class="media-left">
                        <p class="image is-64x64">
                        <img src="https://bulma.io/images/placeholders/128x128.png">
                        </p>
                    </figure>
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong><%= tweet.user.name %></strong>
                                <br>
                                <small>
                                <%= time_ago_in_words(tweet.created_at) %> ago</small>
                            </p>
                        </div>
                    </div>
                </article>
            </div>
        </header>
        <div class="card-content">
                <div class="content">
                <h2> <%= tweet.tweet %> </h2>
                <div class="icons" valign="bottom">
                    <%= link_to display_likes_path(tweet), :remote => true do %>
                        <i class="fa fa-gratipay" style="color:red"></i>
                    <% end %>    
                    <small> <%= tweet.likes.count %></small>
                    <%= link_to display_retweets_path(tweet), :remote => true do%>
                        <i class="fa fa-comments"></i> 
                    <% end %>
                    <small> <%= tweet.retweets.count %></small>
                </div>
            </div>
        </div>
    
        <footer class="card-footer">
            <%= link_to tweet_path(tweet),class: ' card-footer-item'  do %>
                <i class="fa fa-retweet"></i>
            <% end %>
        </footer>
    </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="column is-6 is-offset-3">
    <div class="card">
        <header class="card-header">
            <div class="box" style="width: 100%">
                <article class="media">
                    <figure class="media-left">
                        <p class="image is-64x64">
                        <img src="https://bulma.io/images/placeholders/128x128.png">
                        </p>
                    </figure>
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong><%= tweet.user.name %></strong>
                                <br>
                                <small>
                                <%= time_ago_in_words(tweet.created_at) %> ago</small>
                            </p>
                        </div>
                    </div>
                </article>
            </div>
        </header>
        <div class="card-content">
                <div class="content">
                <br>
                <h2> <%= tweet.tweet %> </h2>
                <br>
                <br>
                <%= link_to display_likes_path(tweet), :remote => true do %>
                    <i class="fa fa-gratipay" style="color:red"></i>
                <% end %>    
                <small> <%= tweet.likes.count %></small>
                <%= link_to display_retweets_path(tweet), :remote => true do%>
                    <i class="fa fa-comments"></i> 
                <% end %>
                <small> <%= tweet.retweets.count %></small>
            </div>
        </div>
        
            <footer class="card-footer">
                <% if logged_in?  %>
                    <% if local_assigns[:show] %>
                        <% if post_liked?(tweet) %>
                            <%= link_to tweet_like_path(tweet) ,method: :delete,class: ' card-footer-item' do %>
                                <i class="fa fa-heart" style="color:red"></i>
                            <% end %>
                        <% else %>
                            <%= link_to tweet_likes_path(tweet) ,method: :post,class: ' card-footer-item' do %>
                                <i class="fa fa-heart"></i>
                            <% end %>
                        <% end %>
                    <% else %>
                        <% if  user_equals?(tweet.user) %>
                            <%= link_to edit_tweet_path(tweet),class: ' card-footer-item' do %>
                                <i class="fa fa-edit"></i>
                            <% end %>
                        <% end %>
                    <% end %>
                    <% if user_equals?(tweet.user)%>
                        <%= link_to tweet_path(tweet),class: ' card-footer-item', method: :delete, data: {confirm: "Are u sure u want to delete this tweet?"} do %>
                            <i class="fa fa-trash"></i>
                        <% end %>
                    <% end %>
                <% end %>
                <% if local_assigns[:show] %>
                    <%= link_to root_path ,class: ' card-footer-item' do %>
                        <i class="fa fa-reply"></i>
                    <% end %>
                <% else %>
                    <%= link_to tweet_path(tweet),class: ' card-footer-item'  do %>
                        <i class="fa fa-retweet"></i>
                    <% end %>
                <% end %>
            </footer>
    </div>
</div>
<% if local_assigns[:show] %> 
        <div class="column is-6 is-offset-3">
            <!-- SHould be inside card -->
            <div class="card">
                <div class="box" style="width: 100%">
                    <article class="media">
                        <figure class="media-left">
                            <p>
                                <code> Retweets </code>  
                            </p>
                        </figure>
                    </article>
                    <%= render partial:'retweets/retweet', collection: tweet.retweets %>
                </div>
            </div>
            <% if logged_in? %>
                <br>
                <%= render 'retweets/form', tweet: tweet, retweets: tweet.retweets.build %>
            <% end %>
        </div>
<% end %>

app/views/tweets/display_likes.js.erb
$('.modal-card-title').text('Likes')
$('.modal-card-body').html("<%= j render partial:'likes/like', collection: @tweet.likes %>");

app/views/tweets/display_retweets.js.erb
$('.modal-card-title').text('Retweets')
$('.modal-card-body').html("<%= j render partial:'retweets/retweet', collection: @tweet.retweets %>");

app/views/tweets/edit.html.erb
<%= render 'form',tweet: @tweet,button_name: "Update Tweet",our_path: tweet_path %>

app/views/tweets/index.html.erb
<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
        <p class="modal-card-title">Modal title</p>
        <button class="delete" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
        <!-- Content ... -->
        </section>
        <footer class="modal-card-foot">
        <button class="button">Cancel</button>
        </footer>
    </div>
  </div>
</div>
<div class="columns is-multiline">
  <div class="column is-6 is-offset-3">
    <h2 class="title"> All tweets </h2>
  </div>
  <%= render @tweets %>
</div>

app/views/tweets/new.html.erb
<%= render 'form', tweet: @tweet, button_name: "Create Tweet", our_path: tweets_path %>

app/views/tweets/show.html.erb
<%= render @tweet, show: true %>