config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resources :retweets
    resources :likes, only: [ :create, :destroy]
  end
  
  # Creating these for using .js.erb for displaying likes adn retweets in root_path
  get '/displaylikes/:id', to: 'tweets#display_likes', as: :display_likes
  get '/displayretweets/:id', to: 'tweets#display_retweets', as: :display_retweets

  namespace :auths do
    get '/users/signup', to: 'users#new'
    resources :users, except: :new

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end
  root 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<div class="columns is-multiline">  
    <div class="column is-6 is-offset-3">
        
        <% flash.each do |name,msg| %>
          <article class="message is-<%= name %>">
            <div class="message-header">
              <% if name == 'success' %>
                <p>Everything is OK!</p>
              <% else %>
                <p> Something went wrong </p>
              <% end %>
            </div>
            <div class="message-body">
              <%= msg %>
            </div>
          </article>
        <% end %>
    </div>
</div>

app/views/shared/_footer.html.erb
<br>
<hr>
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>TwitterClone</strong> by <code> Krenar Darlishta </code>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
      is licensed <a href="http://github.com/Krenar123" target="_blank">Krenar123</a>.
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<section class="hero is-dark">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head ">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          
          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu navbar__hover">  
          <h2 class="subtitle logo"> 
            <i class="fa fa-twitter"></i>
            <%= link_to 'Twitter Clone',root_path,class: 'navbar-item main__item' %>
          </h2>
          <div class="navbar-end">
            <%= link_to 'All tweets', tweets_path,class: 'navbar-item all__item' %>
            <% if current_user %>
              <%= link_to 'Create tweets', new_tweet_path, class: 'navbar-item all__item' %>
              <%= link_to 'Profile', auths_user_path(current_user), class: 'navbar-item all__item' %>
              <%= link_to 'Log Out', auths_logout_path,method: :delete, class: 'navbar-item all__item' %>
            <% else %>
              <%= link_to 'Log In', auths_login_path, class: 'navbar-item all__item' %>
              <%= link_to 'Sign Up', auths_users_signup_path, class: 'navbar-item all__item' %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </div>
</section>

app/views/shared/_post_ads.html.erb
<h2 class="title"> Most likely tweets </h2>
<div class="columns" style="background: rgb(255,255,255);background: linear-gradient(90deg, rgba(255,255,255,1) 0%, rgba(157,228,248,1) 50%, rgba(255,255,255,1) 100%);">
    <% most_likely_tweets.each do |tweet| %>
        <%= render 'tweets/six_tweets', tweet: tweet %>
    <% end %>
</div>