config/routes.rb
Rails.application.routes.draw do
  resources :tweets do
    resources :retweets
    resources :likes, only: [ :create, :destroy]
  end
  
  # Creating these for using .js.erb for displaying likes adn retweets in root_path
  get '/displaylikes/:id', to: 'tweets#display_likes', as: :display_likes
  get '/displayretweets/:id', to: 'tweets#display_retweets', as: :display_retweets

  namespace :auths do
    get '/users/signup', to: 'users#new'
    resources :users, except: :new

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end
  root 'tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    MIN_PASS_LENGTH = 6
    MAX_PASS_LENGTH = 20
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    VALID_PASSWORD = /\A      # Must contain 8 or more characters
        (?=.*\d)           # Must contain a digit
        (?=.*[a-z])        # Must contain a lower case character
        (?=.*[A-Z])        # Must contain an upper case character
        (?=.*[[:^alnum:]]) # Must contain a symbol
    /x

    has_secure_password

    has_many :tweets, dependent: :destroy
    has_many :retweets, dependent: :destroy
    has_many :likes, dependent: :destroy
    
    before_save :downcase_email, :capitalize_name
    
    validates :password,length:{ in: (MIN_PASS_LENGTH)..(MAX_PASS_LENGTH), message: 'must contain at least 6 characters'},
    format: {with: VALID_PASSWORD, message: 'must contain digit, lower case, upper case and symbol'}
    validates :name,:email, presence: true
    validates :email,format: {with: VALID_EMAIL_REGEX},
                    case_sensitive: false,
                    uniqueness: {message: 'already exists.'}         

    private

    def downcase_email
        self.email = email.downcase
    end

    def capitalize_name
        self.name = name.capitalize
    end
end

app/controllers/auths/sessions_controller.rb
class Auths::SessionsController < ApplicationController
    skip_before_action :require_login, only: [:new, :create]
    
    def new
    end

    def create
        user = User.find_by(email: params[:ss][:email].downcase).try(:authenticate, params[:ss][:password])
        # Alternative -- User.find_by(email: params[:ss][:email])&.authenticate(params[:ss][:password])
        if user
            log_in(user)
            redirect_to auths_user_path(user)
        else
            flash.now[:danger] = "Email and password doesnt match"
            render :new
        end
    end

    def destroy
        logout
        redirect_to root_path
    end
end

app/controllers/auths/users_controller.rb
class Auths::UsersController < ApplicationController
    skip_before_action :require_login, only: [:new, :show, :create]
    before_action :find_user, except: [:new, :create]
    before_action :correct_user, only: [:edit, :update]

    def new 
        @user = User.new
    end

    def show 
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to auths_user_path(@user)
        else
            render :edit 
        end
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            redirect_to auths_user_path(@user)
        else
            flash.now[:danger] = @user.errors.full_messages.to_sentence
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end

    def find_user
        @user = User.find(params[:id])
    end

    def correct_user
        unless user_equals?(@user)
            flash[:danger] = "You dont have permission!"
            redirect_to root_path
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new
    end

    def show 
        @user = User.find(params[:id])
    end

    def create 
        @user = User.new(user_params)

        if @user.save
            redirect_to @user
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auths/users/_form.html.erb
<article class="media">
    
    <div class="media-content">
        <%= form_with model: [:auths,user], local: true do |form| %>
            <div class="field">
                <%= form.label :name, class:"label" %>
                <p class="control">
                    <%= form.text_field :name, class:"input",placeholder:"Name.." %>
                </p>
            </div>
            <div class="field">
                <%= form.label :email, class:"label" %>
                <p class="control">
                    <%= form.email_field :email, class:"input",placeholder:"Email.." %>
                </p>
            </div>
            <div class="field">
                <%= form.label :password, class:"label" %>
                <p class="control">
                    <%= form.password_field :password, class:"input",placeholder:"Password..." %>
                </p>
            </div>
            <div class="field">
                <%= form.label :password_confirmation, class:"label" %>
                <p class="control">
                    <%= form.password_field :password_confirmation, class:"input",placeholder:"Confirm password..." %>
                </p>
            </div>
            <div class="field">
                <p class="control">
                    <%= form.submit button_name,class:"button" %>
                </p>
            </div>
        <% end %>
    </div>
</article>

app/views/auths/users/_user.html.erb
<div class="box">
    <article class="media">
        <figure class="media-left">
            <p class="image is-128x128">
            <img src="https://bulma.io/images/placeholders/128x128.png">
            </p>
        </figure>
        <div class="media-content">
            <div class="content">
                <p>
                    <h4><strong><%= user.name %></strong></h4>
                    <%= user.email %> 
                    <% if logged_in? &&  user_equals?(@user) %>
                        <%= link_to 'Edit profile',edit_auths_user_path(user), style: 'position:relative; float:right'  %>
                    <% end %>
                    <br>
                    <hr>
                    <code> <%= "All Tweets #{user.tweets.count}" %> · <%= "All Retweets #{user.retweets.count}" %> · <%= "All Likes #{user.likes.count}" %> </code>
                </p>
            </div>
        </div>
    </article>
</div>

app/views/auths/users/edit.html.erb
<div class="columns is-multiline">  
    <div class="column is-6 is-offset-3">
        <%= render 'form', user: @user, button_name: 'Save changes' %>
    </div>
</div>

app/views/auths/users/new.html.erb
<div class="columns is-multiline">  
    <div class="column is-6 is-offset-3">
        <%= render 'form', user: @user, button_name: 'Sign up' %>
    </div>
</div>

app/views/auths/users/show.html.erb
<div class="columns is-multiline">  
    <div class="column is-8 is-offset-2">
        <%= render @user %>
    </div>
</div>
<%= render partial: 'tweets/tweet', collection: @user.tweets %>